### ISSUE TITLE
ZCML files are not installed

### ISSUE THREAD

**Issue by msiedlarek** [Pylons/pyramid_zcml#6]
```
$ pip install git+git://github.com/Pylons/pyramid_zcml.git
Downloading/unpacking git+git://github.com/Pylons/pyramid_zcml.git
  Cloning git://github.com/Pylons/pyramid_zcml.git to /var/folders/6h/f70v1__j0md83g1_xsb6qb240000gn/T/pip-3v2kr8-build
  Running setup.py egg_info for package from git+git://github.com/Pylons/pyramid_zcml.git
    
Requirement already up-to-date: pyramid>=1.4dev in ./environment/lib/python3.3/site-packages/pyramid-1.4-py3.3.egg (from pyramid-zcml==1.0dev)
Requirement already up-to-date: zope.configuration>=3.8.0dev in ./environment/lib/python3.3/site-packages (from pyramid-zcml==1.0dev)
Requirement already up-to-date: distribute in ./environment/lib/python3.3/site-packages/distribute-0.6.34-py3.3.egg (from pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: Chameleon>=1.2.3 in ./environment/lib/python3.3/site-packages/Chameleon-2.11-py3.3.egg (from pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: Mako>=0.3.6 in ./environment/lib/python3.3/site-packages/Mako-0.7.3-py3.3.egg (from pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: WebOb>=1.2b3 in ./environment/lib/python3.3/site-packages/WebOb-1.2.3-py3.3.egg (from pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: repoze.lru>=0.4 in ./environment/lib/python3.3/site-packages/repoze.lru-0.6-py3.3.egg (from pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: zope.interface>=3.8.0 in ./environment/lib/python3.3/site-packages (from pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: zope.deprecation>=3.5.0 in ./environment/lib/python3.3/site-packages/zope.deprecation-4.0.2-py3.3.egg (from pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: venusian>=1.0a3 in ./environment/lib/python3.3/site-packages/venusian-1.0a7-py3.3.egg (from pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: translationstring>=0.4 in ./environment/lib/python3.3/site-packages/translationstring-1.1-py3.3.egg (from pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: PasteDeploy>=1.5.0 in ./environment/lib/python3.3/site-packages/PasteDeploy-1.5.0-py3.3.egg (from pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: zope.i18nmessageid in ./environment/lib/python3.3/site-packages (from zope.configuration>=3.8.0dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: zope.schema in ./environment/lib/python3.3/site-packages (from zope.configuration>=3.8.0dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: MarkupSafe>=0.9.2 in ./environment/lib/python3.3/site-packages/MarkupSafe-0.15-py3.3-macosx-10.8-x86_64.egg (from Mako>=0.3.6->pyramid>=1.4dev->pyramid-zcml==1.0dev)
Requirement already up-to-date: zope.event in ./environment/lib/python3.3/site-packages (from zope.schema->zope.configuration>=3.8.0dev->pyramid-zcml==1.0dev)
Installing collected packages: pyramid-zcml
  Running setup.py install for pyramid-zcml
    
Successfully installed pyramid-zcml
Cleaning up...
```
```
$ ls environment/lib/python3.3/site-packages/pyramid_zcml
__init__.py __pycache__ _compat.py  scaffolds   tests
```
```
$ pserve configuration/development.ini
Traceback (most recent call last):
  File "/Users/msiedlarek/Projects/someproject/environment/lib/python3.3/site-packages/zope/configuration/xmlconfig.py", line 272, in endElementNS
    self.context.end()
  File "/Users/msiedlarek/Projects/someproject/environment/lib/python3.3/site-packages/zope/configuration/config.py", line 345, in end
    self.stack.pop().finish()
  File "/Users/msiedlarek/Projects/someproject/environment/lib/python3.3/site-packages/zope/configuration/config.py", line 453, in finish
    actions = self.handler(context, **args)
  File "/Users/msiedlarek/Projects/someproject/environment/lib/python3.3/site-packages/zope/configuration/xmlconfig.py", line 395, in include
    with openInOrPlain(path) as f:
  File "/Users/msiedlarek/Projects/someproject/environment/lib/python3.3/site-packages/zope/configuration/xmlconfig.py", line 309, in openInOrPlain
    return open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/msiedlarek/Projects/someproject/environment/lib/python3.3/site-packages/pyramid_zcml/configure.zcml'
```

**Comment by tseaver** [comment]
We won't add `MANIFEST.in` until we adopt a project-wide means of keeping it in sync w/ files checked into git.  In the meanwhile, if you must use a `git+git://` target, install `setuptools_git`.
